// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SporticoApp.Infrastructure.Persistence;

#nullable disable

namespace SporticoApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522180016_AddEmailVerificationTokenToUsers")]
    partial class AddEmailVerificationTokenToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SporticoApp.Core.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("chat_rooms_pkey");

                    b.HasIndex(new[] { "User1Id" }, "idx_chat_rooms_user1");

                    b.HasIndex(new[] { "User2Id" }, "idx_chat_rooms_user2");

                    b.HasIndex(new[] { "User1Id", "User2Id" }, "uq_chat_rooms_pair")
                        .IsUnique();

                    b.ToTable("chat_rooms", null, t =>
                        {
                            t.HasComment("Phòng chat 1-1 giữa 2 user");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingPosts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying")
                        .HasComment("pending | active | expired | cancelled");

                    b.HasKey("Id")
                        .HasName("coach_packages_pkey");

                    b.HasIndex("PackageId");

                    b.HasIndex(new[] { "CoachId" }, "idx_coach_packages_coach");

                    b.HasIndex(new[] { "Status", "EndDate" }, "idx_coach_packages_status")
                        .HasFilter("((status)::text = 'active'::text)");

                    b.ToTable("coach_packages", null, t =>
                        {
                            t.HasComment("Lịch sử mua gói của coach");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Headline")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValueSql("0.00")
                        .HasComment("Cache: trung bình rating từ bảng reviews");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Cache: tổng số review");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("coach_profiles_pkey");

                    b.HasIndex(new[] { "Rating", "TotalReviews" }, "idx_coach_profiles_rating")
                        .IsDescending();

                    b.ToTable("coach_profiles", null, t =>
                        {
                            t.HasComment("Hồ sơ huấn luyện viên");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachSport", b =>
                {
                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CoachId", "SportId")
                        .HasName("coach_sports_pkey");

                    b.HasIndex(new[] { "SportId" }, "idx_coach_sports_sport");

                    b.ToTable("coach_sports", null, t =>
                        {
                            t.HasComment("Many-to-many: coach dạy những môn nào");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FollowerId", "FollowingId")
                        .HasName("follows_pkey");

                    b.HasIndex(new[] { "FollowingId" }, "idx_follows_following");

                    b.ToTable("follows", null, t =>
                        {
                            t.HasComment("User theo dõi user khác (chủ yếu learner follow coach)");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.LearnerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("learner_profiles_pkey");

                    b.ToTable("learner_profiles", null, t =>
                        {
                            t.HasComment("Hồ sơ học viên");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("messages_pkey");

                    b.HasIndex(new[] { "RoomId", "SentAt" }, "idx_messages_room")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SenderId" }, "idx_messages_sender");

                    b.HasIndex(new[] { "RoomId", "IsRead" }, "idx_messages_unread")
                        .HasFilter("(is_read = false)");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasComment("Tin nhắn trong phòng chat");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("message_attachments_pkey");

                    b.HasIndex(new[] { "MessageId" }, "idx_message_attachments_message");

                    b.ToTable("message_attachments", null, t =>
                        {
                            t.HasComment("File đính kèm tin nhắn (image, video, doc...)");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("message | review | follow | payment | package | system | report");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "idx_notifications_unread")
                        .HasFilter("(is_read = false)");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_notifications_user")
                        .IsDescending(false, true);

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasComment("Thông báo cho user");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxPosts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id")
                        .HasName("packages_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_packages_active")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "Name" }, "packages_name_key")
                        .IsUnique();

                    b.ToTable("packages", null, t =>
                        {
                            t.HasComment("Gói dịch vụ dành cho coach (basic, pro, premium...)");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasComment("ID của đối tượng được thanh toán (vd: coach_packages.id)");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Polymorphic: liên kết với coach_package hoặc đối tượng khác");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_payments_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "ReferenceType", "ReferenceId" }, "idx_payments_reference");

                    b.HasIndex(new[] { "Status" }, "idx_payments_status");

                    b.HasIndex(new[] { "UserId" }, "idx_payments_user");

                    b.HasIndex(new[] { "TransactionCode" }, "payments_transaction_code_key")
                        .IsUnique();

                    b.ToTable("payments", null, t =>
                        {
                            t.HasComment("Giao dịch thanh toán");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<Guid>("payment_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("payment_transactions_pkey");

                    b.HasIndex(new[] { "payment_id" }, "idx_payment_transactions_payment");

                    b.ToTable("payment_transactions", null, t =>
                        {
                            t.HasComment("Log raw response từ payment gateway (audit trail)");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'draft'::character varying")
                        .HasComment("draft | published | archived | rejected");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("posts_pkey");

                    b.HasIndex(new[] { "CoachId" }, "idx_posts_coach");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_posts_created_at")
                        .IsDescending()
                        .HasFilter("((status)::text = 'published'::text)");

                    b.HasIndex(new[] { "SportId" }, "idx_posts_sport");

                    b.HasIndex(new[] { "Status" }, "idx_posts_status")
                        .HasFilter("((status)::text = 'published'::text)");

                    b.ToTable("posts", null, t =>
                        {
                            t.HasComment("Bài đăng dịch vụ huấn luyện");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("post_images_pkey");

                    b.HasIndex(new[] { "PostId", "OrderIndex" }, "idx_post_images_post");

                    b.ToTable("post_images", null, t =>
                        {
                            t.HasComment("Hình ảnh kèm bài đăng");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'pending'::character varying")
                        .HasComment("pending | reviewing | resolved | rejected");

                    b.Property<Guid>("reporter_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("target_user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("reports_pkey");

                    b.HasIndex("reporter_id");

                    b.HasIndex(new[] { "Status" }, "idx_reports_status")
                        .HasFilter("((status)::text = ANY ((ARRAY['pending'::character varying, 'reviewing'::character varying])::text[]))");

                    b.HasIndex(new[] { "target_user_id" }, "idx_reports_target");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasComment("Báo cáo vi phạm");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("learner_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex(new[] { "CoachId" }, "idx_reviews_coach");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_reviews_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "learner_id" }, "idx_reviews_learner");

                    b.HasIndex(new[] { "PostId" }, "idx_reviews_post")
                        .HasFilter("(post_id IS NOT NULL)");

                    b.HasIndex(new[] { "CoachId", "learner_id" }, "uq_reviews_pair")
                        .IsUnique();

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasComment("Đánh giá từ learner cho coach");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("Danh sách vai trò: admin, coach, learner");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasComment("URL-friendly identifier, vd: cau-long, bong-da");

                    b.HasKey("Id")
                        .HasName("sports_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_sports_active")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "Name" }, "sports_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "sports_slug_key")
                        .IsUnique();

                    b.ToTable("sports", null, t =>
                        {
                            t.HasComment("Danh mục môn thể thao");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'active'::character varying")
                        .HasComment("active | inactive | banned | pending");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_users_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "Status" }, "idx_users_status")
                        .HasFilter("((status)::text <> 'active'::text)");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Bảng người dùng cốt lõi");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "RoleId" }, "idx_user_roles_role");

                    b.ToTable("user_roles", null, t =>
                        {
                            t.HasComment("Many-to-many giữa users và roles");
                        });
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.VCoach", b =>
                {
                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CoachSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("citext");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Headline")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<List<string>>("Sports")
                        .HasColumnType("character varying[]");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("v_coaches", (string)null);
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.VPublishedPost", b =>
                {
                    b.Property<string>("CoachAvatar")
                        .HasColumnType("text");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoachName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("CoachRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int?>("CoachTotalReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("SportId")
                        .HasColumnType("integer");

                    b.Property<string>("SportName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SportSlug")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable((string)null);

                    b.ToView("v_published_posts", (string)null);
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.ChatRoom", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "User1")
                        .WithMany("ChatRoomsAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_rooms_user1");

                    b.HasOne("SporticoApp.Core.Entities.User", "User2")
                        .WithMany("ChatRoomsAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_rooms_user2");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachPackage", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.CoachProfile", "Coach")
                        .WithMany("CoachPackages")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_packages_coach");

                    b.HasOne("SporticoApp.Core.Entities.Package", "Package")
                        .WithMany("CoachPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coach_packages_package");

                    b.Navigation("Coach");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachProfile", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "User")
                        .WithOne("CoachProfile")
                        .HasForeignKey("SporticoApp.Core.Entities.CoachProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_profiles_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachSport", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.CoachProfile", "Coach")
                        .WithMany("CoachSports")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_sports_coach");

                    b.HasOne("SporticoApp.Core.Entities.Sport", "Sport")
                        .WithMany("CoachSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coach_sports_sport");

                    b.Navigation("Coach");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Follow", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "follower")
                        .WithMany("FollowsAsFollower")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_follower");

                    b.HasOne("SporticoApp.Core.Entities.User", "following")
                        .WithMany("FollowsAsFollowing")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_following");

                    b.Navigation("follower");

                    b.Navigation("following");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.LearnerProfile", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "User")
                        .WithOne("LearnerProfile")
                        .HasForeignKey("SporticoApp.Core.Entities.LearnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_profiles_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Message", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.ChatRoom", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_room");

                    b.HasOne("SporticoApp.Core.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_sender");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.MessageAttachment", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.Message", "Message")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachments_message");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Notification", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Payment", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.Payment", "Payment")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("payment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transactions_payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Post", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.CoachProfile", "Coach")
                        .WithMany("Posts")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_coach");

                    b.HasOne("SporticoApp.Core.Entities.Sport", "Sport")
                        .WithMany("Posts")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_sport");

                    b.Navigation("Coach");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.PostImage", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_images_post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Report", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.User", "reporter")
                        .WithMany("ReportsAsReporter")
                        .HasForeignKey("reporter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_reporter");

                    b.HasOne("SporticoApp.Core.Entities.User", "target_user")
                        .WithMany("ReportsAsTargetUser")
                        .HasForeignKey("target_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_target");

                    b.Navigation("reporter");

                    b.Navigation("target_user");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Review", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.CoachProfile", "Coach")
                        .WithMany("Reviews")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_coach");

                    b.HasOne("SporticoApp.Core.Entities.Post", "Post")
                        .WithMany("Reviews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reviews_post");

                    b.HasOne("SporticoApp.Core.Entities.User", "learner")
                        .WithMany("Reviews")
                        .HasForeignKey("learner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_learner");

                    b.Navigation("Coach");

                    b.Navigation("Post");

                    b.Navigation("learner");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.UserRole", b =>
                {
                    b.HasOne("SporticoApp.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("SporticoApp.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.CoachProfile", b =>
                {
                    b.Navigation("CoachPackages");

                    b.Navigation("CoachSports");

                    b.Navigation("Posts");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Message", b =>
                {
                    b.Navigation("MessageAttachments");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Package", b =>
                {
                    b.Navigation("CoachPackages");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Payment", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Post", b =>
                {
                    b.Navigation("PostImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.Sport", b =>
                {
                    b.Navigation("CoachSports");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SporticoApp.Core.Entities.User", b =>
                {
                    b.Navigation("ChatRoomsAsUser1");

                    b.Navigation("ChatRoomsAsUser2");

                    b.Navigation("CoachProfile");

                    b.Navigation("FollowsAsFollower");

                    b.Navigation("FollowsAsFollowing");

                    b.Navigation("LearnerProfile");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("ReportsAsReporter");

                    b.Navigation("ReportsAsTargetUser");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
