name: Build and deploy ASP.Net Core app to Azure Web App - sportico-api-khoi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore SporticoApp.Api/SporticoApp.Api.csproj
      
      - name: Build
        run: dotnet build SporticoApp.Api/SporticoApp.Api.csproj -c Release --no-restore
      
      - name: Publish
        run: dotnet publish SporticoApp.Api/SporticoApp.Api.csproj -c Release -o myapp --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D67869290EE440D0BB7B817969D1179A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7351004924A44489408BC66977E4478 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_359811C931E14CA1BA3681A53A64FEE8 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: sportico-api-khoi
          package: .
